-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Especie"
(
    id_especies integer NOT NULL,
    nombre_comun character varying(30) NOT NULL,
    nombre_cientifico character varying(30) NOT NULL,
    id_descripcion integer NOT NULL,
    id_zona integer NOT NULL,
    PRIMARY KEY (id_especies)
);

CREATE TABLE public."Habitat"
(
    id_habitat integer NOT NULL,
    nombre character varying(30) NOT NULL,
    id_tipo_habitat integer NOT NULL,
    id_continente integer NOT NULL,
    PRIMARY KEY (id_habitat)
);

CREATE TABLE public."Tipo_habitat"
(
    id_tipo_habitat integer NOT NULL,
    clima character varying(30) NOT NULL,
    tipo_vegetacion character varying(30) NOT NULL,
    PRIMARY KEY (id_tipo_habitat)
);

CREATE TABLE public."Continente"
(
    id_continente integer NOT NULL,
    nombre character varying(30) NOT NULL,
    PRIMARY KEY (id_continente)
);

CREATE TABLE public."Especie_Habitat"
(
    "Especie_id_habitat" integer NOT NULL,
    "Habitat_id_habitat" integer NOT NULL,
    "id_Especie_Habitat" integer NOT NULL,
    PRIMARY KEY ("id_Especie_Habitat")
);

CREATE TABLE public."Descripcion_especie"
(
    id_descripcion integer NOT NULL,
    sexo character varying(1) NOT NULL,
    fecha_nacimiento date NOT NULL,
    peso double precision NOT NULL,
    PRIMARY KEY (id_descripcion)
);

CREATE TABLE public."Zona"
(
    id_zona integer NOT NULL,
    nombre character varying(30) NOT NULL,
    extension_territorial double precision NOT NULL,
    PRIMARY KEY (id_zona)
);

CREATE TABLE public."Itinerarios"
(
    codigo character varying(30) NOT NULL,
    id_duracion_recorrido integer NOT NULL,
    longitud_recorrido double precision NOT NULL,
    numero_maximodevisitante_autorizados integer NOT NULL,
    numero_dedistintasespecies_quevisita integer NOT NULL,
    PRIMARY KEY (codigo)
);

CREATE TABLE public."Duraccion_recorrido"
(
    id_duracion_recorrido integer NOT NULL,
    hora integer NOT NULL,
    minutos integer NOT NULL,
    segundos integer NOT NULL,
    PRIMARY KEY (id_duracion_recorrido)
);

CREATE TABLE public."Lista_dezonas_visitadas"
(
    id_tours integer NOT NULL,
    codigo character varying(30) NOT NULL,
    id_zona integer NOT NULL,
    PRIMARY KEY (id_tours)
);

CREATE TABLE public."Empleados"
(
    id_empleado integer NOT NULL,
    primer_nombre character varying(30) NOT NULL,
    segundo_nombre character varying(30),
    primer_apellido character varying(30) NOT NULL,
    segundo_apellido character varying(30) NOT NULL,
    id_direccion integer NOT NULL,
    id_telefono integer NOT NULL,
    id_correo integer NOT NULL,
    PRIMARY KEY (id_empleado)
);

CREATE TABLE public."Direccion"
(
    id_direccion integer NOT NULL,
    pais character varying(30) NOT NULL,
    provincia character varying(30) NOT NULL,
    canton character varying(30) NOT NULL,
    distrito character varying(30) NOT NULL,
    barrio character varying(30) NOT NULL,
    PRIMARY KEY (id_direccion)
);

CREATE TABLE public."Telefono"
(
    id_telefono integer NOT NULL,
    numero_celular_personal integer NOT NULL,
    numero_telefono_laboral integer,
    numero_telefono_secundario integer,
    PRIMARY KEY (id_telefono)
);

CREATE TABLE public."Correo"
(
    id_correo integer NOT NULL,
    correo_personal character varying(30) NOT NULL,
    correo_laboral character varying(30),
    correo_secundario character varying(30),
    PRIMARY KEY (id_correo)
);

CREATE TABLE public."Guia"
(
    id_guia integer NOT NULL,
    id_empleado integer NOT NULL,
    fecha_deingreso_laboral date NOT NULL,
    PRIMARY KEY (id_guia)
);

CREATE TABLE public."Asignaciones"
(
    id_asignaciones integer NOT NULL,
    hora_comiezo time without time zone NOT NULL,
    id_guia integer NOT NULL,
    codigo character varying(30) NOT NULL,
    PRIMARY KEY (id_asignaciones)
);

CREATE TABLE public."Cuidadores"
(
    id_cuidador integer NOT NULL,
    fecha_ingreso_alparque date NOT NULL,
    PRIMARY KEY (id_cuidador)
);

CREATE TABLE public."Cuidador_especie"
(
    id_cuido integer NOT NULL,
    fecha_de__inicio_cuido date NOT NULL,
    id_especies integer NOT NULL,
    id_cuidador integer NOT NULL,
    PRIMARY KEY (id_cuido)
);

ALTER TABLE public."Habitat"
    ADD FOREIGN KEY (id_tipo_habitat)
    REFERENCES public."Tipo_habitat" (id_tipo_habitat)
    NOT VALID;


ALTER TABLE public."Habitat"
    ADD FOREIGN KEY (id_continente)
    REFERENCES public."Continente" (id_continente)
    NOT VALID;


ALTER TABLE public."Especie_Habitat"
    ADD FOREIGN KEY ("Habitat_id_habitat")
    REFERENCES public."Habitat" (id_habitat)
    NOT VALID;


ALTER TABLE public."Especie"
    ADD FOREIGN KEY (id_descripcion)
    REFERENCES public."Descripcion_especie" (id_descripcion)
    NOT VALID;


ALTER TABLE public."Itinerarios"
    ADD FOREIGN KEY (id_duracion_recorrido)
    REFERENCES public."Duraccion_recorrido" (id_duracion_recorrido)
    NOT VALID;


ALTER TABLE public."Lista_dezonas_visitadas"
    ADD FOREIGN KEY (codigo)
    REFERENCES public."Itinerarios" (codigo)
    NOT VALID;


ALTER TABLE public."Lista_dezonas_visitadas"
    ADD FOREIGN KEY (id_zona)
    REFERENCES public."Zona" (id_zona)
    NOT VALID;


ALTER TABLE public."Empleados"
    ADD FOREIGN KEY (id_direccion)
    REFERENCES public."Direccion" (id_direccion)
    NOT VALID;


ALTER TABLE public."Empleados"
    ADD FOREIGN KEY (id_telefono)
    REFERENCES public."Telefono" (id_telefono)
    NOT VALID;


ALTER TABLE public."Empleados"
    ADD FOREIGN KEY (id_correo)
    REFERENCES public."Correo" (id_correo)
    NOT VALID;


ALTER TABLE public."Guia"
    ADD FOREIGN KEY (id_empleado)
    REFERENCES public."Empleados" (id_empleado)
    NOT VALID;


ALTER TABLE public."Asignaciones"
    ADD FOREIGN KEY (id_guia)
    REFERENCES public."Guia" (id_guia)
    NOT VALID;


ALTER TABLE public."Asignaciones"
    ADD FOREIGN KEY (codigo)
    REFERENCES public."Itinerarios" (codigo)
    NOT VALID;


ALTER TABLE public."Cuidador_especie"
    ADD FOREIGN KEY (id_especies)
    REFERENCES public."Especie" (id_especies)
    NOT VALID;


ALTER TABLE public."Cuidador_especie"
    ADD FOREIGN KEY (id_cuidador)
    REFERENCES public."Cuidadores" (id_cuidador)
    NOT VALID;


ALTER TABLE public."Especie_Habitat"
    ADD FOREIGN KEY ("Especie_id_habitat")
    REFERENCES public."Especie" (id_especies)
    NOT VALID;


ALTER TABLE public."Especie"
    ADD FOREIGN KEY (id_zona)
    REFERENCES public."Zona" (id_zona)
    NOT VALID;

END;